name: workflow building blocks

# for more info on triggers -> google "events that trigger worflows"
# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  push:
    branches: # what if you want to blanket do action on push regardless of branch?
      - main #insert branches you want to insert here
  pull_request:
    branches:
      - main
    paths: #just like branches can be a filter, so can the path within repo
      - '.github/**' #pull requests with any changes within `.github` directory & sub-directories will trigger
  workflow_dispatch: #another type of trigger, allows triggering workflow manually with some inputs we specify below
    inputs:
      outputValue:
        description: 'Value to output'
        required: false
        default: 'hello world'
  repository_dispatch: #trigger -> allows us to run workflow by making API call to github
    types: [hello_world] #why is this in square brackets??
  schedule: #eg: "i want my workflow to run at X time a specific day/everyday")
    - cron: "1 * * * *" #is there a difference in single quotes vs double quotes for github actions?

permissions:
  pull-requests: write #giving action express persission to also write

#the actual tasks that will be performed
#NOTE: each job is completely independent from one another -> can be run on different machines
jobs: 
  #first job
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: hello-world #why his there a line in front of name but not ID? can we list multiple names or is it for this step? (diff between thsi and brances on triggers???)
        id: hello-world
        run: | # pipe!!!
          echo "Hello World!!!"
          hello_world="Hello World!!!"
          echo "value=${hello_world}" >> $GITHUB_OUTPUT

      # second step
      - name: comment on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.hello-world.outputs.value }}
  

  hello-universe:
    #needs: [hello-world] # is this like an if statement? or will it throw an error
    runs-on: ubuntu-latest
    steps:
      - name: hello-universe
        id: hello-universe
        run: |
          hello_universe="Hello Universe!!!"
          echo ${{ hello_universe }}
          echo "value=${hello_universe}" >> $GITHUB_OUPUT
      
      - name: comment on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evants/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.hello-universe.outputs.value }}
            
